<a href="https://colab.research.google.com/github/Yas19-bit/yash/blob/Data/labelencoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skt
from sklearn.preprocessing import LabelEncoder

In [4]:
df=pd.read_csv('/content/loan.csv')
df.head()

,UID,Marital_status,Dependents,Is_graduate,Income,Loan_amount,Term_months,Credit_score,approval_status,Age,Sex,Purpose,Hobby
0,LP001002,NO,0,Graduate,45848,NaN,360.0,1.0,0,40.0,Male,Education,Reading
1,LP001002,NO,0,Graduate,45848,NaN,360.0,1.0,0,40.0,Male,Education,Reading
2,LP001003,YES,1,Graduate,15325,128.0,360.0,1.0,1,22.0,Male,Education,Reading
3,LP001005,YES,0,Graduate,29105,66.0,360.0,1.0,0,27.0,Male,Education,Reading
4,LP001006,YES,0,Not Graduate,42944,120.0,360.0,1.0,0,36.0,F,Education,Reading

In [9]:
df['Hobby'].unique()

array(['Reading', 'Watching Movie'], dtype=object)

In [8]:
le=LabelEncoder()
df['Hobbye']=le.fit_transform(df['Hobby'])
df

,UID,Marital_status,Dependents,Is_graduate,Income,Loan_amount,Term_months,Credit_score,approval_status,Age,Sex,Purpose,Hobby,Hobbye
0,LP001002,NO,0,Graduate,45848,NaN,360.0,1.0,0,40.0,Male,Education,Reading,0
1,LP001002,NO,0,Graduate,45848,NaN,360.0,1.0,0,40.0,Male,Education,Reading,0
2,LP001003,YES,1,Graduate,15325,128.0,360.0,1.0,1,22.0,Male,Education,Reading,0
3,LP001005,YES,0,Graduate,29105,66.0,360.0,1.0,0,27.0,Male,Education,Reading,0
4,LP001006,YES,0,Not Graduate,42944,120.0,360.0,1.0,0,36.0,F,Education,Reading,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,LP002978,No,0,Graduate,19515,71.0,360.0,1.0,1,55.0,Female,Travel,Watching Movie,1
611,LP002979,Yes,3+,Graduate,30004,40.0,180.0,1.0,1,47.0,Male,Wedding,Watching Movie,1
612,LP002983,Yes,1,Graduate,39788,253.0,360.0,1.0,1,27.0,Male,Wedding,Watching Movie,1
613,LP002984,Yes,2,Graduate,37984,187.0,360.0,1.0,0,47.0,Male,Wedding,Watching Movie,1
614,LP002990,No,0,Graduate,23743,133.0,360.0,0.0,1,42.0,Female,Travel,Watching Movie,1